# -*- coding: utf-8 -*-
"""simple linear regrresion project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yp2BvTDoUMna_5FkHwV9vkKIAbLXarBW
"""

# import libaries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# to upload data
data = pd.read_csv("/content/50_Startups.csv")

data.head()

data.shape

data.describe()

data.isnull().sum()

data.duplicated().sum()

data.info()

data.corr(numeric_only=True)

sns.heatmap(data.corr(numeric_only=True) ,annot=True)
plt.show()

outliers = ["Profit"]
plt.rcParams["figure.figsize"] = [4,4]
sns.boxplot(data=data[outliers],orient="v",palette="husl",width=0.7)
plt.title("outliers variable distribution")
plt.ylabel("profit range")
plt.show()

sns.boxplot(x = "State",y= "Profit", data= data)
plt.show()

sns.histplot(data["Profit"],bins=5,kde=True)
plt.show()

sns.pairplot(data)
plt.show()

# preparing data
x = data[["R&D Spend", "Administration","Marketing Spend"]]
y = data["Profit"]
x = x.to_numpy()
y = y.to_numpy()
y = y.reshape(-1,1)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
ypred = model.predict(x_test)
data = pd.DataFrame(data={"Predicted Profit" : ypred.flatten()})
print(data.head())

test_data_model_score = model.score(x_test,y_test)
print("Model Score/Performance on Testing data",test_data_model_score)
training_data_model_score = model.score(x_train,y_train)
print("Model Score/Performance on Training data",training_data_model_score)

df = pd.DataFrame({"Actual Profit":y_test.flatten(),"Predicted Profit":ypred.flatten()})
df

# evalutate the model
from sklearn.metrics import r2_score
r2score = r2_score(ypred,y_test)
print("R2 Score of the model is: ",r2score*100)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(ypred,y_test)
print("Mean Sqaurred  error of the model is: ",mse*100)

rmse = np.sqrt(mse)
print("Root Mean Sqaurred  error of the model is: ",rmse*100)
#

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(ypred,y_test)
print("Mean Absolute error of the model is: ",mae)